<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e2de613e-aec5-4288-b6fc-d1ced77e5fba</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_docs_intro</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/docs\/intro']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navbar__item navbar__link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navbar__item navbar__link</value>
        <webElementGuid>6b3b0927-d087-459b-bdaf-8d644053d8b6</webElementGuid>
    </webElementProperties>
</WebElementEntity>