<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e95d4607-4741-42f0-b52b-51783251fe4b</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_faqs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/div[1]/a[5]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/faqs']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navbar__item navbar__link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navbar__item navbar__link</value>
        <webElementGuid>bd637584-a3fb-401a-9723-aef2c6846857</webElementGuid>
    </webElementProperties>
</WebElementEntity>